### PR TITLE
std::initializer_list without constexpr

### PR DESCRIPTION
**Pull request by 2bbb**
cite: https://github.com/arturoc/openFrameworks/commit/481b55df7712d6e167028fee96cb45ddccb1747b#commitcomment-14945104

### CODE REVIEW

**Comment by arturoc** [comment]
great thanks!, can you remove the commented lines? if everything is working with that i think we can just remove them from there

**Comment by 2bbb** [comment]
okay, i deleted those and pushed. :+1:

**Comment by arturoc** [comment]
thanks!

**Comment by 2bbb** [comment]
not at all!
many japanese users expect this feature!!

**Pull request merged**
