### PR TITLE
add changes necessary for visual studio flavour

### PR DESCRIPTION
**Pull request by tgfrerer**
+ add unset TMP, TEMP so that there's no clash with these environment
  variables upon calling CL.exe

+ fixed deployment target paths for 32 and 64 bit

### CODE REVIEW

**Comment by tgfrerer** [comment]
one thing to notice is that the recipe does not overwrite the old library files, since these have the CV version number in their filename -- also, the current addons/cvexamples have the libraries hardcoded, so will still link against the old libraries, unless the project files are re-generated. 

it might be an idea to add a step of cleaning the target directories of old static libs before copying the newly compiles static libs in. 

Tested both 32 and 64 bit versions.

**Comment by arturoc** [comment]
yes in other formulas i've added code in the copy section to delete the old files otherwise there might be old files that are not there anymore and won't get overwritten. can you add that? and also commit the binary files so i can merge it into master.

**Comment by tgfrerer** [comment]
I've cleaned up the recipe somehow, and added the binary libs. Not 100% sure if the old libs are deleted in the repository, though.

**Comment by arturoc** [comment]
doesn't seem so, you probably haven't commited them?

**Comment by arturoc** [comment]
i mean doesn't seem like it has deleted the old ones from the repo you need to commit the deletions too

**Comment by tgfrerer** [comment]
Yes, the deletions didn't show up on my diff. seems they need to be added by force, I'll see to it after lunch.

**Comment by tgfrerer** [comment]
done -- pls double-check...

**Comment by arturoc** [comment]
the commits look correct, the diff is showing an infinite symbol which is scary but i think is just a github glitch, i'm going to merge it and see what happens

**Comment by tgfrerer** [comment]
yes that ∞ is well scary. but it should be ok - all in all it's about 72 * 2 binary + 2 text files changed.

**Pull request merged**
